name       : libxmu
version    : 1.1.2
release    : 6
source     :
    - http://xorg.freedesktop.org/releases/individual/lib/libXmu-1.1.2.tar.bz2 : 756edc7c383254eef8b4e1b733c3bf1dc061b523c9f9833ac7058378b8349d0b
license    :
    - MIT
summary    : X11 miscellaneous utility library
component  : xorg.library
builddeps  :
    - pkgconfig(x11)
    - pkgconfig32(x11)
    - pkgconfig(xext)
    - pkgconfig32(xext)
    - pkgconfig(xt)
    - pkgconfig32(xt)
emul32     : yes
optimize   : speed
description: |
    This library contains miscellaneous utilities and is not part of the Xlib standard.  It contains routines which only use public interfaces so that it may be layered on top of any proprietary implementation of Xlib or Xt
setup      : |
    %configure --with-appdefaultdir=/etc/X11/app-defaults \
               --disable-static
build      : |
    %make
install    : |
    %make_install
